spring.application.name=User-Service
server.port=8081
app.jwt.secret = "MySuperSecretKeyForJwtToken123456"
app.jwt.expiration-ms = 86400000

# Eureka properties
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#DB config
spring.datasource.url=jdbc:postgresql://localhost:5433/UserServiceDb
spring.datasource.username=aaaa
spring.datasource.password=aaaa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

